### ISSUE TITLE
Command failed  

### ISSUE THREAD

**Issue by DaniyalGeek** [yasharma/mongo-to-csv#4]
{ Error: Command failed: mongoexport --type csv -d muddy -c user -f user_name -o ./pets.csv
Error parsing command line: unknown option type
try 'mongoexport --help' for more information

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
  killed: false,
  code: 2,
  signal: null,
  cmd: 'mongoexport --type csv -d muddy -c user -f user_name -o ./pets.csv' }
Error parsing command line: unknown option type
try 'mongoexport --help' for more information

**Comment by DaniyalGeek** [comment]
change line number 51  ==>     let arr = ['mongoexport', '--type=csv'] with    let arr = ['mongoexport']

then it start working can you check?

**Comment by Rogify** [comment]
> 
> 
> change line number 51 ==> let arr = ['mongoexport', '--type=csv'] with let arr = ['mongoexport']
> 
> then it start working can you check?

You probably already got this working, but in the first post, you have written `--type csv`, while it should have been `--type=csv`. When you use `['mongoexport']` instead of `['mongoexport', '--type=csv']`, Mongoexport actually exports the data in .json form.
